name: Daily Auto Update Workflow

# Menjalankan secara otomatis setiap hari pada pukul 00:00 (UTC)
on:
  schedule:
    - cron: '0 */4 * * *'  # Setiap 4 jam pada menit ke-0

jobs:
  update-repo:
    runs-on: ubuntu-latest  # Menjalankan di server Ubuntu
    steps:
      - name: Checkout repository  # Mengambil kode dari repository "Penghijauan"
        uses: actions/checkout@v2
        with:
          repository: MyartGalela/Penghijauan  # Ganti dengan username dan repository yang benar

      - name: Pull changes from GitHub  # Menarik perubahan terbaru dari branch 'main'
        run: git pull origin main

      - name: Check for README changes  # Memeriksa apakah README.md berubah
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'README.md'; then
            echo "README.md has changed"
          else
            echo "No changes in README.md"
          fi

      - name: Increment README change count  # Menambahkan hitungan perubahan jika README.md berubah
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'README.md'; then
            echo "README.md has changed. Incrementing count."
            COUNT=$(grep -oP '(?<=Total Changes: )\d+' README.md)
            COUNT=$((COUNT + 1))
            sed -i "s/Total Changes: [0-9]*/Total Changes: $COUNT/" README.md
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add README.md
            git commit -m "Increment README.md change count to $COUNT"
            git push origin main
          fi
