name: CI

on:
  push:
    branches:
      - main  # Ganti dengan nama branch kamu jika perlu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import --batch --yes
      
      - name: Configure Git to use GPG
        run: |
          git config --global user.signingkey F77FA5C7E92588A756B36E606FD5D53407B2C619
          git config --global commit.gpgSign true

      - name: Make Changes
        run: |
          # Tambahkan perintah untuk membuat perubahan di repository
          echo "Some changes" >> changes.txt
          git add changes.txt
          git commit -m "Add changes" -S  # Menandatangani komit
          git push  # Mengirimkan perubahan
